image : python:3.6

before_script:
  - apt-get update -qq && apt-get install -y -qq python-pip pandoc
  - pip install numpy flake8 pytest pytest-flake8
  - pip install -r requirements.txt
  - pip install -e .

flake8:
  script:
    - export RENOM_PRECISION=64
    - flake8 .

pytest:
  script:
    - cd test
    - export RENOM_PRECISION=64
    - pytest
